### ISSUE TITLE
How to add blog collection to it?

### ISSUE THREAD

**Issue by rajasekhar-gundala** [one-ie/ONE#3]
Thank you very much for the theme. It looks good.

Is there a way to add blog collection to it? I tried to create Content folder, posts folder inside it. But no look.

do the needful.

**Comment by tonyoconnell** [comment]
I actually had a blog in it while I would building it but I took it out to keep things as simple as possible. To add one in again just create a new Astro site with npm create astro@latest check add blog then copy over the content folder and the pages to display the blog.

**Comment by tonyoconnell** [comment]
OK. I added /stream to demonstrate how content collections work in Astro 5. You can rename it to blog if you like.

**Comment by rajasekhar-gundala** [comment]
> OK. I added /stream to demonstrate how content collections work in Astro 5. You can rename it to blog if you like.

Thank you very much for it. It would be good to have back to blog or stream link on post page or related posts below the post.
